# Code : Square Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    4444
    4444
    4444
    4444
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 50
    Sample Input 1:
    7
    Sample Output 1:
    7777777
    7777777
    7777777
    7777777
    7777777
    7777777
    7777777
    Sample Input 1:
    6
    Sample Output 1:
    666666
    666666
    666666
    666666
    666666
    666666

In [ ]:
## Read input as specified in the question
## Print the required output in given format
n=int(input())
for i in range(n):
    for j in range(n):
        print(n,end='')
    print()

# Code : Triangular Star Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    *
    **
    ***
    ****
    Note : There are no spaces between the stars (*).
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
    *
    **
    ***
    ****
    *****
    Sample Input 2:
    6
    Sample Output 2:
    *
    **
    ***
    ****
    *****
    ******

In [ ]:
## Read input as specified in the question
## Print the required output in given format
n=int(input())
for i in range(n+1):
    for j in range(i):
        print('*',end='')
    print()

# Code : Triangle Number Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    1
    22
    333
    4444
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
    1
    22
    333
    4444
    55555
    Sample Input 2:
    6
    Sample Output 2:
    1
    22
    333
    4444
    55555
    666666

In [ ]:
## Read input as specified in the question
## Print the required output in given format
n=int(input())
for i in range(n+1):
    for j in range(i):
        print(i,end='')
    print()

# Code : Reverse Number Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    1
    21
    321
    4321
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
    1
    21
    321
    4321
    54321
    Sample Input 2:
    6
    Sample Output 2:
    1
    21
    321
    4321
    54321
    654321

In [ ]:
## Read input as specified in the question
## Print the required output in given format

n=int(input())
for i in range(n+1):
    k=i
    for j in range(i):
        print(k,end='')
        k-=1
    print()

# Code : Alpha Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 3
     A
     BB
     CCC
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 26
    Sample Input 1:
    7
    Sample Output 1:
    A
    BB
    CCC
    DDDD
    EEEEE
    FFFFFF
    GGGGGGG
    Sample Input 2:
    6
    Sample Output 2:
    A
    BB
    CCC
    DDDD
    EEEEE
    FFFFFF

In [ ]:
## Read input as specified in the question.
## Print output as specified in the question.
num = int(input())
i=1
while i<=num:
    c=chr(ord('A')+i-1)
    j=1
    while j<=i:
        print(c,end='')
        j+=1    
    print()
    i+=1

# Code : Character Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    A
    BC
    CDE
    DEFG
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 13
    Sample Input 1:
    5
    Sample Output 1:
    A
    BC
    CDE
    DEFG
    EFGHI
    Sample Input 2:
    6
    Sample Output 2:
    A
    BC
    CDE
    DEFG
    EFGHI
    FGHIJK

In [ ]:
## Read input as specified in the question
## Print the required output in given format
num=int(input())
for i in range(1,num+1):
    k=i
    for j in range(1,i+1):

        print(chr(64+k),end='')
        k+=1
    print()

# Code : Interesting Alphabets
    Print the following pattern for the given number of rows.
    Pattern for N = 5
    E
    DE
    CDE
    BCDE
    ABCDE
    Input format :
    N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 26
    Sample Input 1:
    8
    Sample Output 1:
    H
    GH
    FGH
    EFGH
    DEFGH
    CDEFGH
    BCDEFGH
    ABCDEFGH
    Sample Input 2:
    7
    Sample Output 2:
    G
    FG
    EFG
    DEFG
    CDEFG
    BCDEFG
    ABCDEFGH

In [ ]:
## Read input as specified in the question.
## Print output as specified in the question.
num=int(input())

for i in range(1,num+1):
    k=65+num -i
    for j in range(1,i+1):

        print(chr(k),end='')
        k+=1
    print()

# Code : Inverted Number Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4
    4444
    333
    22
    1
    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints :
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
    55555 
    4444
    333
    22
    1
    Sample Input 2:
    6
    Sample Output 2:
    666666
    55555 
    4444
    333
    22
    1

In [ ]:
## Read input as specified in the question
## Print the required output in given format

num=int(input())
for i in range(num,0,-1):
    for j in range(i,0,-1):
        print(i,end='')
    print()

# Code : Mirror Number Pattern
    Print the following pattern for the given N number of rows.
    Pattern for N = 4




    The dots represent spaces.


    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints
    0 <= N <= 50
    Sample Input 1:
    3
    Sample Output 1:
          1 
        12
      123
    Sample Input 2:
    4
    Sample Output 2:
          1 
        12
      123
    1234

In [ ]:
## Read input as specified in the question
## Print the required output in given format
n = int(input())
for i in range(1, n + 1):
    k = 1
    for j in range(1, n + 1):

        if j >= (n + 1) - i:
            print(k, end = '')
            k += 1
        else:
            print(' ',end='')
        
    print()

# Code : Star Pattern
    Print the following pattern
    Pattern for N = 4



    The dots represent spaces.



    Input Format :
    N (Total no. of rows)
    Output Format :
    Pattern in N lines
    Constraints :
    0 <= N <= 50
    Sample Input 1 :
    3
    Sample Output 1 :
       *
      *** 
     *****
    Sample Input 2 :
    4
    Sample Output 2 :
        *
       *** 
      *****
     *******

In [ ]:
## Read input as specified in the question.
## Print output as specified in the question.

n=int(input())

for i in range(1,n+1):
    
    for j in range(1,n*2):
        
        if j>=n+1-i and j<=n-1+i:
            print('*',end='')
        elif j<=n-1+i:
            print(' ',end='')
    print()

# Code : Triangle of Numbers
    Print the following pattern for the given number of rows.
    Pattern for N = 4



    The dots represent spaces.



    Input format :
    Integer N (Total no. of rows)
    Output format :
    Pattern in N lines
    Constraints :
    0 <= N <= 50
    Sample Input 1:
    5
    Sample Output 1:
               1
             232
           34543
         4567654
       567898765
    Sample Input 2:
    4
    Sample Output 2:
               1
             232
           34543
         4567654

In [ ]:
## Read input as specified in the question.
## Print output as specified in the question.
n=int(input())


for i in range(1,n+1):
    k=i
    for j in range(1,n*2):
        
        if j>=n+1-i and j<=n-1+i:
            if j>n:
                k-=1
                print(k,end='')
                
            elif j<n:
                print(k,end='')
                k+=1
            else:
                print(k,end='')
        elif j<=n-1+i:
            print(' ',end='')
    print()

# Code : Diamond of stars
    Print the following pattern for the given number of rows.
    Note: N is always odd.


    Pattern for N = 5



    The dots represent spaces.



    Input format :
    N (Total no. of rows and can only be odd)
    Output format :
    Pattern in N lines
    Constraints :
    1 <= N <= 49
    Sample Input 1:
    5
    Sample Output 1:
      *
     ***
    *****
     ***
      *
    Sample Input 2:
    3
    Sample Output 2:
      *
     ***
      *

In [ ]:
n1 = int(input())
n=(n1+1)/2
i=1
k=1
k1=1
while i<=n1:
    if i<=n:
        s=1
        while s<=n-i:
            print(' ',end='')
            s+=1
        s1=1
        while s1<=i:
            print('*',end='')
            s1+=1
        s2=i-1
        while s2>=1:
            print('*',end='')
            s2-=1
    
    if i>n:
        r=1
        while r<=i-n:
            print(' ',end='')
            r+=1
        s=1
        while s<=n-k:
            print('*',end='')
            s+=1
        s1=1
        while s1<=n-k1-1:
            print('*',end='')
            s1+=1
        k1+=1
        k+=1 
    print()
    i+=1